# Site settings
title: M151B
subtitle: Computer Systems Architecture

baseurl: "/m151b" # the subpath of your site, e.g. /blog/
url: "https://tinebp.github.io" # the base hostname & protocol for your site
#syllabus: ""
#githubdir: ""

# Author/user information
#email: svmille@clemson.edu
#twitter_username: stevenvmiller
#github_username:  svmiller
#authorurl: "http://svmiller.com"
#address: |
#    Department of Political Science
#    232 Brackett Hall
#    Clemson, SC 29634-1354


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
